# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70e40b10a1cbcde6dfcca0ab137dab7f01b3ee74d07c1b00f8172d1664226e9e4ec076c922be02fc9e80994f989e7f65ede5d2075668455a8bf240a3912538fd

test:
  secret_key_base: 8629e9ecc6d7f49807294fc25f02d7e979b8faac5f549adc940b5c2656af81d1fb88b3db4366f5a5164c472770873bd0ef123415e100cb52a65c0d55ad3596d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
